/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 portfolio04.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/portfolio04.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials.circlePlatform}
        position={[-62.164, -0.004, -133.957]}
        rotation={[0, 0.097, 0]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials.circlePlatform}
        position={[-69.367, 0.003, -135.99]}
        rotation={[0, 0.862, 0]}
      />
      <mesh
        geometry={nodes.archWall01.geometry}
        material={materials.walls}
        position={[-104.611, 5.354, -159.279]}
        rotation={[0, -0.817, 0]}
      />
      <mesh
        geometry={nodes.archWall01001.geometry}
        material={materials.walls}
        position={[-92.549, 5.354, -172.955]}
        rotation={[0, -0.578, 0]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.ocean}
        position={[-94.265, 1.248, -159.12]}
        rotation={[0, -0.701, 0]}
      />
      <mesh
        geometry={nodes.Icosphere001.geometry}
        material={materials.sculpture}
        position={[-149.762, 13.073, -210.081]}
        rotation={[-1.156, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials.walls}
        position={[-60.858, 1.25, -132.936]}
        rotation={[0, -0.663, 0]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.roofEntrance}
        position={[0.565, 4.3, -8.255]}
        scale={[1, 0.836, 1]}
      />
      <mesh
        geometry={nodes.entranceRoofGlass.geometry}
        material={materials['Roof Glass']}
        position={[0.837, 4.165, -8.272]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials.floorEntrance}
        position={[1.368, -1.078, 100.563]}
      />
      <mesh
        geometry={nodes.Landscape001.geometry}
        material={materials.rock}
        position={[9.565, 0.784, -5.172]}
        rotation={[-0.589, 0.785, 1.361]}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials.floorInterior}
        position={[-1.738, 0.001, -30.89]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials.floorInterior}
        position={[6.446, 0.001, -60.331]}
      />
      <mesh
        geometry={nodes.BezierCurve.geometry}
        material={materials.floorInterior}
        position={[-5.586, 0.001, -86.258]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[2.279, -0.019, -70.591]}
      />
      <mesh
        geometry={nodes.Landscape002.geometry}
        material={materials.rock}
        position={[-8.348, 0.615, -3.996]}
        rotation={[-2.187, -0.154, -1.726]}
      />
      <mesh
        geometry={nodes.Landscape003.geometry}
        material={materials.rock}
        position={[13.706, -0.38, -1.042]}
        rotation={[-2.62, -0.017, -2.525]}
      />
      <mesh
        geometry={nodes.Landscape004.geometry}
        material={materials.rock}
        position={[-12.522, -0.38, -1.903]}
        rotation={[0.248, 0.216, 1.711]}
      />
      <mesh
        geometry={nodes.entrance01.geometry}
        material={materials.walls}
        position={[0, -0.028, -13.737]}
      />
      <mesh
        geometry={nodes.entranceCurvedWall.geometry}
        material={materials.walls}
        position={[-2.9, 4.431, -18.037]}
      />
      <mesh
        geometry={nodes.floor.geometry}
        material={materials.floorInterior}
        position={[0.183, 0, -19.383]}
      />
      <mesh
        geometry={nodes.pedestal02.geometry}
        material={materials.circlePlatform}
        position={[-5.211, 0.496, -30.827]}
      />
      <mesh
        geometry={nodes.entranceSphere.geometry}
        material={materials.sculpture}
        position={[-5.211, 1.668, -30.827]}
      />
      <mesh
        geometry={nodes.entranceRoofCutout.geometry}
        material={materials.walls}
        position={[-5.209, 7.766, -30.899]}
      />
      <mesh
        geometry={nodes.straightRoom.geometry}
        material={materials.walls}
        position={[6.191, -0.001, -41.53]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[12.035, 3, -53.036]}
        rotation={[0, -0.42, 0]}
        scale={[1.629, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.circularRoom.geometry}
        material={materials.walls}
        position={[-38.268, 0.726, -114.098]}
        rotation={[0, -0.113, 0]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials.walls}
        position={[-39.042, 0.991, -118.189]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.circlePlatform}
        position={[-38.268, 0.16, -114.098]}
      />
      <mesh
        geometry={nodes.TorusKnot.geometry}
        material={materials.sculpture}
        position={[-38.268, 4.353, -114.098]}
        rotation={[0.118, 0.573, -0.109]}
      />
      <mesh
        geometry={nodes.water.geometry}
        material={materials['Material.004']}
        position={[-38.268, 0.126, -114.098]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials.benches}
        position={[-4.492, 0.235, -49.039]}
        rotation={[0, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials.benches}
        position={[-11.588, 0.235, -89.045]}
        rotation={[-Math.PI, -1.389, 0]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials.walls}
        position={[10.297, 13.829, -80.145]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials.walls}
        position={[1.025, 13.875, -97.349]}
      />
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={materials.sculpture}
        position={[16.275, 0.664, -73.274]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials['pillar.001']}
        position={[16.643, 0, -31.631]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials['pillar.001']}
        position={[16.643, 0, -35.363]}
      />
      <mesh
        geometry={nodes.Canvas01.geometry}
        material={materials.Canvas001}
        position={[12.035, 3, -53.036]}
        rotation={[0, -0.42, 0]}
        scale={[1.63, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.entranceRoof.geometry}
        material={materials.walls}
        position={[0, -0.039, -13.737]}
      />
      <mesh
        geometry={nodes.floor001.geometry}
        material={materials.floorEntrance}
        position={[0.183, 0, -19.383]}
      />
      <mesh
        geometry={nodes.entrance02001.geometry}
        material={materials.walls}
        position={[-1.231, 5.329, -29.409]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials.benches}
        position={[12.409, 0.235, -31.067]}
        rotation={[Math.PI, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials.benches}
        position={[17.132, 0.235, -39.579]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[-0.069, 3, -72.55]}
        rotation={[0, 0.413, 0]}
        scale={[1.629, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Canvas01001.geometry}
        material={materials.Canvas001}
        position={[-0.069, 3, -72.55]}
        rotation={[0, 0.413, 0]}
        scale={[1.63, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[10.63, 3, -92.398]}
        rotation={[0, -0.45, 0]}
        scale={[1.629, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Canvas01002.geometry}
        material={materials.Canvas001}
        position={[10.63, 3, -92.398]}
        rotation={[0, -0.45, 0]}
        scale={[1.63, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[-10.216, 3, -110.056]}
        rotation={[0, 0.554, 0]}
        scale={[1.629, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Canvas01003.geometry}
        material={materials.Canvas001}
        position={[-10.216, 3, -110.056]}
        rotation={[0, 0.554, 0]}
        scale={[1.63, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-30.974, 3, -89.757]}
        rotation={[-Math.PI, 0.859, -Math.PI]}
        scale={[1.629, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Canvas01004.geometry}
        material={materials.Canvas001}
        position={[-30.974, 3, -89.757]}
        rotation={[-Math.PI, 0.859, -Math.PI]}
        scale={[1.63, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-59.154, 3, -98.602]}
        rotation={[0, 1.48, 0]}
        scale={[1.629, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Canvas01005.geometry}
        material={materials.Canvas001}
        position={[-59.154, 3, -98.602]}
        rotation={[0, 1.48, 0]}
        scale={[1.63, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[-64.587, 3, -118.668]}
        rotation={[0, 0.709, 0]}
        scale={[1.629, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Canvas01006.geometry}
        material={materials.Canvas001}
        position={[-64.587, 3, -118.668]}
        rotation={[0, 0.709, 0]}
        scale={[1.63, 1.225, 1.225]}
      />
      <mesh
        geometry={nodes.Sorento_Sculpture.geometry}
        material={materials.sculpture}
        position={[-53.53, 0.004, -137.858]}
      />
      <mesh
        geometry={nodes.Human_walking_18m.geometry}
        material={materials.benches}
        position={[15.009, -0.045, -46.33]}
        rotation={[Math.PI, -0.302, Math.PI]}
        scale={1.095}
      />
      <mesh
        geometry={nodes.Human_walking_18m001.geometry}
        material={materials.benches}
        position={[-21.263, -0.045, -90.278]}
        rotation={[0, -1.34, 0]}
        scale={1.095}
      />
    </group>
  );
}

useGLTF.preload('/portfolio04.glb');
